### ISSUE TITLE
Potential drift correction bug for CO floe grid 30-second segments?

### ISSUE THREAD

**Issue by ajutila** [awi-als-toolbox/awi-als-toolbox#29]
Could it be that the drift correction is not stored in the individual 30-second segments of CO floe grids? In the screen shot below, left is the overview plot that combines all individual 30-second segments of freeboard from `20200616_01_PS122-4_44-78_Heli-PS/l4/icecs_freeboard` and right is the merged grid of the same flight. 

![image](https://user-images.githubusercontent.com/45628873/172584852-8aff4500-7bd2-428c-bab8-71dd9377a51c.png)

**Comment by nhutter** [comment]
Ok, the not ice drift corrected lat/lon in the 30s-segments are caused by [here](https://github.com/awi-als-toolbox/awi-als-toolbox/blob/b8ce04efd4085049b71cf05cd5ae4154ab460733/awi_als_toolbox/_grid.py#L230). The lat/lon are drift corrected, but relative to the center time of the 30s segment, which is not useful at all. The reference time for all segments need to be the same and equal to the center time of the entire floe grid survey.

**Comment by nhutter** [comment]
I added a reference time attribute to the ice drift correction that is used to compute the lat/lon values in both 30s segments and floe grid. The reference time is part of the config files and is automatically set for the MOSAiC processing. The reference time is exported in the attributes of the netcdf files of 30-s segments as `reference_time_drift_correction`. Tests of gridding individual l1b-files were successful and test of the full processing round for an entire floe grid is in the queue for ollie. Once successful, I will create a pull request.
